services:
  marva-quartz:
    image: node:23
    working_dir: /app
    ports:
      - "4444:4444"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_KEYCLOAK_AUTH_PATH: "http://localhost:8081/keycloak/"
    command: sh -lc "npm install && npm run dev-external -- --host"
