services:
  marva-quartz:
    build: .
    ports:
      - "4444:4444"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      #- VITE_KEYCLOAK_AUTH_PATH=http://localhost:8081/keycloak/ # Workflows Keycloak path
      - VITE_KEYCLOAK_AUTH_PATH=http://localhost/keycloak/       # Terraform Keycloak path
      #- VITE_BLUECORE_API_URL=https://bcld.info
      - VITE_BLUECORE_API_URL=http://localhost
    command: ["npm", "run", "dev-external", "--", "--host"]
